### model
model_name_or_path: saves/baselines/Qwen2-VL-7B-Instruct-128k
flash_attn: fa2
infer_dtype: bfloat16

### method
stage: sft
do_predict: true
finetuning_type: full

### dataset
eval_dataset: lvbench
template: qwen2_vl
cutoff_len: 131072
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 2

### data
video_fps: 2
video_frame_extraction_fps: 25
video_maxlen: 256
video_resolution: 448

### generate
do_sample: false

### output
output_dir: saves/qwen2vl_7b_128k_lvbench_f256_r448/lf_predict
overwrite_output_dir: true

### eval
per_device_eval_batch_size: 1
predict_with_generate: true
